name: Check
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Prettier
        run: npm run lint:prettier
      - name: ESLint
        run: npm run lint:eslint
      - name: Jest
        run: npm run test
      - name: Build
        run: npm run build
